site_name: PetrSU IMIT Helper
site_url: https://williamadamswag.github.io/PetrSU_IMIT_Helper
site_description: .

copyright: Copyright &copy; 2026 Никита Чесноков

theme:
    name: material
    language: ru
    custom_dir: docs/overrides

    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
                icon: material/brightness-7 
                name: Переключиться на темную тему
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
                icon: material/brightness-4
                name: Переключиться на светлую тему

    features:
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - navigation.expand
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
        - navigation.top
        - navigation.footer
        - search.suggest
        - search.highlight
        - content.code.annotate
        - content.code.copy
        - content.tabs.link
        - consent

nav:
    - Главная: index.md

    - Матанализ:
        - Матанализ: math-analysis/index.md
        - Теория множеств:
            - Введение: math-analysis/set-theory/index.md
            - 1. Основные понятия: math-analysis/set-theory/part1.md
            - 2. Операции над множествами: math-analysis/set-theory/part2.md

    - Аналитическая геометрия:
        - Аналитическая геометрия: analytic-geometry/index.md

    - Алгебра:
        - Алгебра: algebra/index.md

    - ОИиП:
        - Основы информатики и программирования: base_inf_and_prog/index.md
        - Язык С:
            - Введение: base_inf_and_prog/c/index.md
            - Первая программа: base_inf_and_prog/c/hello_world.md
        - Лабы:
            - Hello, Students!: base_inf_and_prog/labs/lab1.md
            - Нужный этаж: base_inf_and_prog/labs/lab2.md
            - Проблема 196: base_inf_and_prog/labs/lab3.md
            - Гипотеза Гольдбаха: base_inf_and_prog/labs/lab4.md
            - Калькулятор рациональных дробей: base_inf_and_prog/labs/lab5.md
            - Англо-русский словарь: base_inf_and_prog/labs/lab6.md
            - Прототип компьютерной игры: base_inf_and_prog/labs/lab7.md

plugins:
    - search
    - tags

markdown_extensions:
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.arithmatex:
        generic: true
    - tables
    - attr_list
    - md_in_html

extra_javascript:
    - javascripts/katex-init.js
    - https://unpkg.com/katex@0/dist/katex.min.js
    - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
    - https://unpkg.com/katex@0/dist/katex.min.css
    - stylesheets/extra.css

extra:
    analytics:
        provider: google
        property: G-3KBPVM4THS
    
    consent:
        title: Согласие на использование cookies
        description: >- 
            Мы используем файлы cookie для оценки посещаемости и улучшения 
            работы нашей документации. Вы можете изменить свои настройки в любой момент.
        actions:
            - accept
            - manage

    giscus:
        repo: WilliamAdamsWAG/PetrSU_IMIT_Helper
        repo_id: R_kgDOUOgTHQ
        category: Q&A
        category_id: DIC_kwDOUOgTHc4DE7WZ
        mapping: pathname
        strict: 0
        reactions_enabled: 1
        emit_metadata: 1
        input_position: top
        theme: preferred_color_scheme
        lang: ru
        crossorigin: anonymous

    social:
        - icon: fontawesome/brands/telegram
          link: https://t.me/WilliamAdams_group
          name: По любым вопросам
