site_name: PetrSU IMIT Helper
site_url: https://williamadamswag.github.io/PetrSU_IMIT_Helper
site_description: .

theme:
    name: material
    language: ru

    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
                icon: material/brightness-7 
                name: Переключиться на темную тему
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
                icon: material/brightness-4
                name: Переключиться на светлую тему

    features:
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - navigation.expand
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
        - navigation.top
        - navigation.footer
        - search.suggest
        - search.highlight
        - content.code.annotate
        - content.code.copy

nav:
    - Главная: index.md

    - Матанализ:
        - Введение: math-analysis/index.md
        - Теория множеств:
            - Введение: math-analysis/set-theory/index.md
            - 1. Основные понятия: math-analysis/set-theory/part1.md

    - Аналитическая геометрия:
        - Введение: analytic-geometry/index.md

    - Алгебра:
        - Введение: algebra/index.md

plugins:
    - search

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.arithmatex:
        generic: true
    - tables
    - attr_list
    - md_in_html

extra_javascript:
    - javascripts/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - stylesheets/extra.css

extra:
    analytics:
        provider: google
        property: G-3KBPVM4THS
    
    consent:
        title: Согласие на использование cookies
        description: >- 
            Мы используем файлы cookie для оценки посещаемости и улучшения 
            работы нашей документации. Вы можете изменить свои настройки в любой момент.
        actions:
            - accept
            - manage

    giscus:
        repo: WilliamAdamsWAG/PetrSU_IMIT_Helper
        repo_id: R_kgDOUOgTHQ
        category: Q&A
        category_id: DIC_kwDOUOgTHc4DE7WZ
        mapping: pathname
        strict: 0
        reactions_enabled: 1
        emit_metadata: 1
        input_position: top
        theme: preferred_color_scheme
        lang: ru
        crossorigin: anonymous
